Feature/ot248 42
alkemyTech/OT248-Server pull request #27
Opened 2022-07-26 01:29 UTC by juanmat11

endpoint to create categories.

2022-07-26 03:48 UTC, turcoamado requested changes

2022-07-26 03:48 UTC, turcoamado commented on src/main/java/com/alkemy/ong/controller/CategoryController.java
> +    @PreAuthorize("hasRole('ROLE_USER')")
Esto no esta mal, pero mejor si directamente se agrega en el archivo de configuracion de jwt, puede que sea mas sencillo luego cuando tengan que realizar los test

2022-07-26 03:48 UTC, turcoamado commented on src/main/java/com/alkemy/ong/dto/CategoryDto.java
> +    @Pattern(regexp = "[a-bA-B0-9]", message = "This field only accepts letters and numbers.")
Muy bueno el uso de la regex!

2022-07-26 03:48 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/CategoryServiceImpl.java
> +        return categoryDto;
No esto no esta bien, porque el objeto que llega no es el mismo que se genera, es un tema de conceptos en realidad porque para este caso la informacion si sera la misma.
Entonces lo que habria que hacer es, primero transformar el DTO a Entity, casi que como lo estas planteando, pero deberia estar abstraido en un metodo, o bien dentro del service o en un mapper, no recuerdo como van a trabajar.
Luego podrias chequear que esa categoria ya existe, es decir si el nombre elegido ya se encuentra, para no guardar dos veces la misma, en caso de existir lanzar una excepcion.
Por ultimo si hacer el save() en el repositorio y al objeto que te devuelve que es una Entity pasarla a DTO mediante otro metodo (el inverso de antes) y ese valor es el que se devuelve hacia el controller

2022-07-26 23:14 UTC, juanmat11 commented on src/main/java/com/alkemy/ong/service/impl/CategoryServiceImpl.java
> +            throw new Exception("There is already a category with this name");
aqui se que dijiste que lo usemos en properties pero lo podre desde el proximo sprint sino no llego

2022-07-28 14:04 UTC, turcoamado approved these changes
Acordate de modificar el preAuthorized y hacete una variable de ese constructor private, con eso listo podes mergear

2022-07-28 14:04 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/CategoryServiceImpl.java
> +        Category categoryDB= categoryRepository.searchCategoryForName(categoryEntity.getName());
Te la rebuscaste un poco pero esta bien, podrias haber hecho directamente la busqueda utilizando el name del dto porque ese es el mismo y si eso te devuelve null entonces haces el mapeo y guardas, el resultado es el mismo pero tal vez es un poco mas sencilla la logica o a nivel procesamiento. No hace falta que lo cambies, solo para que veas otra alternativa
```
public CategoryDto createCategory(CategoryDto categoryDto) throws Exception{
   if (categoryRepository.searchCategoryForName(categoryDto.getName()) == null ) {
         Category category = categoryRepository.save(categoryMapper.CategoryDtoToCategory(categoryDto));
         return categoryMapper.CategoryToCategoryDTO(category);
   } else {
            throw new Exception("There is already a category with this name");
   }
}
```

2022-07-28 14:04 UTC, turcoamado commented on src/main/java/com/alkemy/ong/controller/CategoryController.java
> +    CategoryService categoryService;
esta variable hacela private

2022-07-28 14:04 UTC, turcoamado commented on src/main/java/com/alkemy/ong/controller/CategoryController.java
> +    @PreAuthorize("hasRole('ROLE_USER')")
acordate de modificar este!

2022-07-28 17:20 UTC, merged