Endpoint PUT -> /publics was created on OrganizationController, metho…
alkemyTech/OT248-Server pull request #32
Opened 2022-07-26 22:28 UTC by maxif96

…d updateOrganization was created on OrganizationService

2022-07-27 01:04 UTC, turcoamado requested changes

2022-07-27 01:04 UTC, turcoamado commented on src/main/java/com/alkemy/ong/auth/config/SecurityConfiguration.java
> +                .antMatchers(HttpMethod.PUT, "/organization/public").hasRole("ADMIN")
Lo que charlamos en daily (y ademas se lo cometne a uno de los chicos) ponganse de acuerdo con estos nombres, es mas creo que vos mismo creaste un seeder para establecer nombres de roles, pero chequeen y fijense porque debe haber uno solo. 
Podrian hacer uso de la variable de clase que hay declarada con el nombre que corresponda.

2022-07-27 01:04 UTC, turcoamado commented on src/main/java/com/alkemy/ong/auth/filter/JwtRequestFilter.java
> +//                Authentication auth = authenticationManager.authenticate(authReq);
Esta linea que esta comentada se puede eliminar?

2022-07-27 01:04 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/OrganizationServiceImpl.java
> +        Optional<Organization> organizationEntity = organizationRepository.findFirstByOrderByIdOrganization();
me gusta que hayas utilizado un objeto Optional para esto

2022-07-27 01:04 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/OrganizationServiceImpl.java
> +        Organization organization = Organization.builder()
Esto quizas tambien podria ir a un mapper. No esta mal como lo hiciste, pero dado que utilizas el mapper para el caso contrario este podria estar tambien. Supongo no lo haces por el tema del id y la fecha de creacion, pero esos campos los obtenes desde la entidad tambien, lo primero que haces es buscarla en el repositorio, si existe ya tendra esos datos y no se van a modificar, por lo que no necesitaria setearle nada diferente a lo que ya encontre

2022-07-27 02:37 UTC, maxif96 commented on src/main/java/com/alkemy/ong/auth/config/SecurityConfiguration.java
> +                .antMatchers(HttpMethod.PUT, "/organization/public").hasRole("ADMIN")
Si, ahi comenté por el Slack. Por más que el nombre del rol sea 'ROLE_ADMIN', tira una excepción si lo ponemos así en la configuración, por lo que entendí Spring ya entiende que si pones el nombre del rol sin el ROLE_ así que me parece adecuado que lo pongamos así

2022-07-27 02:37 UTC, maxif96 commented on src/main/java/com/alkemy/ong/auth/filter/JwtRequestFilter.java
> +//                Authentication auth = authenticationManager.authenticate(authReq);
Si, me había olvidado de sacarla

2022-07-27 03:04 UTC, maxif96 commented on src/main/java/com/alkemy/ong/service/impl/OrganizationServiceImpl.java
> +        Organization organization = Organization.builder()
Hecho

2022-07-28 13:47 UTC, turcoamado approved these changes
Buenisimo Maxi! Ojo que cambio el archivo de jwt, hacete un pull de develop y actualizate este branch antes de mergear para estar en sintonia con ese archivo, Juan cambio ya los nombres de los roles

2022-07-28 14:40 UTC, merged