Ticket OT248-40
alkemyTech/OT248-Server pull request #40
Opened 2022-07-29 14:51 UTC by maxif96

• Endpoint GET/ categories was created (Just ADMIN role)
• Method getCategoryNames in Service was created
• Query in repository for get all category names was created

2022-07-29 14:52 UTC, maxif96 commented
![image](https://user-images.githubusercontent.com/87986166/181786413-8fb334f4-cda1-4a20-8e47-bb42acde36ec.png)

2022-07-30 17:25 UTC, turcoamado requested changes

2022-07-30 17:25 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/CategoryServiceImpl.java
>              throw new Exception("There is already a category with this name");
Podrias aprovechar para cambiar este mensaje y ya reescribirlo utilizando el properties de mensajes

2022-07-30 17:25 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/CategoryServiceImpl.java
> +       return categoryRepository.findAllCategoryNames();
Yo le agregaria un mensaje si la lista esta vacia, para no mostrar un json vacio.

2022-08-01 16:32 UTC, maxif96 commented
Cambios solicitados realizados

2022-08-01 23:45 UTC, turcoamado approved these changes
genial!

2022-08-02 01:00 UTC, merged