OT248-52 Crear Seed Data para guardar Actividades existentes de la ONG
alkemyTech/OT248-Server pull request #41
Opened 2022-07-31 15:29 UTC by JonathanRamirez1

2022-08-01 18:19 UTC, turcoamado requested changes
Jonathan te consulto., como realizas la ejecucion de este script? No esta mal pensarlo de esta manera, pero la idea es que se ejecute una unica vez cuando se corre por primera vez la aplicacion.

Unos detalles, el id es autogenerado porl o que no es correcto setearle id en el script, y otra cosa, aca se estaria generando un solo registro, la idea seria poder tener unos cuantos, no se, ponele 10 (ya se que la tarjeta no lo aclara).

Otra alternativa seria mediante codigo java, implementando la interface CommandLineRunner. Entonces se podria crear un package nuevo que se llame seeder ponele, y alli crear esta clase

2022-08-02 01:34 UTC, turcoamado requested changes
Bueno viene por aca, el tema es que estas cargando data como si fuesen usuarios o algo asi. Pensa en actividades ficticias que podria tener una ONG, suponete "Ayuda escolar" no se por decir algo, entonces para ese caso yo pensaria algo del estilo:
```
Activity activity1 = new Activity();
activity1.setName("Ayuda escolar");
        activity.setContent("Brindamos ayuda escolar para chicos de primero a septimo grado en las materias de Lengua, Matematica, Ciencias Naturales y Ciencias Sociales");
        activity1.setImage("http://www.image.com");
        activity1.setCreateAt(date);
        activity1.setUpdateAt(date);
        activity1.setDeleted(false);

activityService.saveActivity(activity1);
```

A modo de ejemplo te puse tambien como podrias guardar cada actividad cargada, se podria implementar de alguna otra manera tambien dentro de un bucle por ejemplo

2022-08-02 01:34 UTC, turcoamado commented on src/main/java/com/alkemy/ong/seeder/ActivityRunner.java
> +        activityService.saveActivity(activity);
Ojo que estas guardando una sola vez, es decir, le seteas datos 10 veces pero persistis una sola activity, la ultima que cargas, entonces estas pisando siempre los valores.

2022-08-02 01:35 UTC, JonathanRamirez1 commented on src/main/java/com/alkemy/ong/seeder/ActivityRunner.java
> +        activityService.saveActivity(activity);
Como podria guardar los 10 datos?

2022-08-02 01:36 UTC, JonathanRamirez1 commented
> Bueno viene por aca, el tema es que estas cargando data como si fuesen usuarios o algo asi. Pensa en actividades ficticias que podria tener una ONG, suponete "Ayuda escolar" no se por decir algo, entonces para ese caso yo pensaria algo del estilo:
> 
> ```
> Activity activity1 = new Activity();
> activity1.setName("Ayuda escolar");
>         activity.setContent("Brindamos ayuda escolar para chicos de primero a septimo grado en las materias de Lengua, Matematica, Ciencias Naturales y Ciencias Sociales");
>         activity1.setImage("http://www.image.com");
>         activity1.setCreateAt(date);
>         activity1.setUpdateAt(date);
>         activity1.setDeleted(false);
> 
> activityService.saveActivity(activity1);
> ```
> 
> A modo de ejemplo te puse tambien como podrias guardar cada actividad cargada, se podria implementar de alguna otra manera tambien dentro de un bucle por ejemplo

Ya lo modifico, lo hice asi para llenar rapido

2022-08-04 02:12 UTC, turcoamado requested changes
La tarea esta bien, pero de donde estas saliendo? veo muchos cambios y deberias tener solo una clase diferente, la del seeder. Antes de mergear deberias chequear bien eso, porque seguramente haya cambios en develop con los merge que van a realizarse, de ultima esperate al final porque total esto no impacta demasiado en el resto de la aplicacion.

Deberias hacerte un merge de develop sobre este branch, pero por lo que veo va a querer seguir incluyendo varios de los cambios

2022-08-04 13:32 UTC, merged