OT248 56
alkemyTech/OT248-Server pull request #43
Opened 2022-07-31 23:14 UTC by maxif96

• SlideResponseDTO was created
• SlideMapper was created
• SlideService and SlideServiceImpl was created
• Endpoint getById() was created
• Only ROLE_ADMIN is able to access to this endpoint
• Exception handled with message.properties
• It return a 404 NOT FOUND

2022-07-31 23:18 UTC, maxif96 commented
Error:

![image](https://user-images.githubusercontent.com/87986166/182049184-492c3c61-bb5a-4179-abbb-976da3b08a5d.png)

Success:

![image](https://user-images.githubusercontent.com/87986166/182049221-91136431-cdab-413a-8359-6847acbb8983.png)

ROLE_USER (Unauthorized):

![image](https://user-images.githubusercontent.com/87986166/182049320-3f34fcef-f0ff-400d-a321-bda989e37c9e.png)

2022-08-01 20:16 UTC, turcoamado requested changes
Te marque dos pavadas, esta muy bien

2022-08-01 20:16 UTC, turcoamado commented on src/main/java/com/alkemy/ong/controller/SlideController.java
> +    SlideService slideService;
hace privada esta variable

2022-08-01 20:16 UTC, turcoamado commented on src/main/resources/locale/messages.properties
> +notfound = with that id not found
te falto un "was" antes de "not", y deberias separarlo como los anteriores, con un punto -> `not.found = wit that id was not found`

2022-08-01 23:27 UTC, maxif96 commented on src/main/java/com/alkemy/ong/controller/SlideController.java
> +    SlideService slideService;
Cada vez son menos las que me olvido de ponerle el private jajaja

2022-08-01 23:27 UTC, maxif96 commented
Added changes requested

2022-08-02 01:12 UTC, turcoamado approved these changes

2022-08-02 01:48 UTC, merged