Ot248 43
alkemyTech/OT248-Server pull request #48
Opened 2022-08-02 16:24 UTC by maxif96

Hice el endpoint para actualizar una Categoría.
Aproveché para limpiar un poco el código en general en varias clases (eliminé imports sin uso, modificadores de acceso public redundantes, etc)

2022-08-02 16:25 UTC, maxif96 commented
Update: 
![image](https://user-images.githubusercontent.com/87986166/182424907-a8098776-9bdd-40fc-baa9-ee1355bbdab0.png)
Error:
![image](https://user-images.githubusercontent.com/87986166/182424958-8db42295-f851-4586-8461-7027ca4f0ffd.png)

2022-08-02 16:25 UTC, maxif96 commented
Hay un commit donde elimino el application propertios mio que pushié por error

2022-08-04 00:30 UTC, turcoamado requested changes
Los cambios en las otras clases estan barbaro, sobre todo el haberle sacado los public a los metodos de las interfaces, se me re paso a mi en la revision.

Te deje un comentario con el tema de la regex que vi que dejaste comentada, eso estaba por el requerimiento de creacion me parece.

Vas a tener que estar atento a los conflictos porque seguramente te pinche con cosas que has sascado

2022-08-04 00:30 UTC, turcoamado commented on src/main/java/com/alkemy/ong/dto/CategoryDto.java
> +//    @Pattern(regexp = "[a-bA-B0-9]", message = "This field only accepts letters and numbers.")
por que comentaste la regex?

2022-08-04 01:37 UTC, maxif96 commented on src/main/java/com/alkemy/ong/dto/CategoryDto.java
> +//    @Pattern(regexp = "[a-bA-B0-9]", message = "This field only accepts letters and numbers.")
Porque me saltaba la validaciòn aùn cuando ingresaba un nombre entre el rango marcado, creo que està mal ahora que lo veo, solo se puede poner letras a y b y nùmeros, pero no otras letras del abecedario, o lo estoy comprendiendo mal. De igual manera lo comentè para testear y luego me olvidè de descomentarlo.

2022-08-04 02:30 UTC, turcoamado commented on src/main/java/com/alkemy/ong/dto/CategoryDto.java
> +//    @Pattern(regexp = "[a-bA-B0-9]", message = "This field only accepts letters and numbers.")
Tenes razon! Nunca la analice, la queres cambiar por esta? `[a-zA-Z0-9]` eso aceptaria cualquier letra y cualquier numero

2022-08-04 23:51 UTC, turcoamado approved these changes
Te lo dejo como aprobado, modificale la RegEx y chequeate los conflictos

2022-08-05 00:13 UTC, merged