Ot248-48
alkemyTech/OT248-Server pull request #49
Opened 2022-08-02 20:01 UTC by emirmoretti

- DELETE /news/:id
![news_delete_postman](https://user-images.githubusercontent.com/71144640/182462692-7a76ee1f-33ba-40ad-9f6c-805f3d4c4ec8.JPG)

2022-08-02 20:17 UTC, turcoamado requested changes

2022-08-02 20:17 UTC, turcoamado commented on src/main/java/com/alkemy/ong/controller/NewsController.java
> +            return new ResponseEntity<>("User deleted", HttpStatus.OK);
Dos cosas aca, primero estas eliminando una novedad y le pones "User deleted", lo otro es que deberia estar en el properties, y ponele algo como _News deleted successfully_ por ejemplo

2022-08-02 20:17 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/NewsServiceImpl.java
> +            throw new NotFoundException("news not found");
Esto ya podriamos agregarlo en el properties de mensajes. De todos modos no es correcta la implementacion, porque estas diciendo que news no fue encontrado en la exception, y en realidad no sabes si fue o no encontrado, esta explotando por algun motivo (si no explota no cae en ese catch). 
Fijate que estas usando un if que dice si esta presente entonces ejecutame el delete, pero si no esta presente no hace nada, por lo tanto si intenta eliminar algo que no existe en la db no lo borra pero no se muestra ningun tipo de mensaje, en este caso deberia mostrarse un 404 y el mensaje indicando que no se encontro

2022-08-02 20:24 UTC, emirmoretti commented on src/main/java/com/alkemy/ong/controller/NewsController.java
> +            return new ResponseEntity<>("User deleted", HttpStatus.OK);
Se me quedo en la cabeza el user de otra cosa, gracias Yamil ahora lo soluciono y lo implemento en el properties

2022-08-03 23:39 UTC, turcoamado approved these changes
Excelentes los cambios

2022-08-03 23:39 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/NewsServiceImpl.java
> +                .orElseThrow(() -> new EntityNotFoundException("News "
Buenisimo!

2022-08-03 23:53 UTC, merged