UserSeedData was created.
alkemyTech/OT248-Server pull request #51
Opened 2022-08-03 01:43 UTC by maxif96

![image](https://user-images.githubusercontent.com/87986166/182505933-e5c20737-de19-4a72-bfff-a1a1270f6a39.png)

2022-08-03 01:53 UTC, maxif96 commented
I added those generated users in the README.txt

2022-08-04 01:46 UTC, turcoamado requested changes
Esto esta bien, pero te falta hacer el Readme que lo pide la tarjeta. Y un detalle, aunque mas fiaca porque por ahi no se puede automatizar como lo hiciste en un bucle, pero le pondria nombres que simulen nombres reales porque es una buena practica. 

Para esto quizas podrias hacer una lista de nombres y otra de apellidos y en el for haces algo similar a esto para obtener el nombre y apellido:
```
    .firstName(nameList.get(i))
    .firstLastName(lastnameList.get(i))
```
y de esta manera estarias obteniendo un nombre y un apellido diferente por cada posicion que recorres, pero debes tener una lista de 20 nombres y una de 20 apellidos

2022-08-04 23:45 UTC, maxif96 commented
![image](https://user-images.githubusercontent.com/87986166/182973534-0a74303e-2732-49c8-80a3-aa53af99f2d6.png)

2022-08-04 23:47 UTC, turcoamado approved these changes

2022-08-17 23:15 UTC, closed without merging